# LuCI Themes
src-git footstrap https://github.com/VizzleTF/luci-theme-footstrap.git
src-git argon https://github.com/jerrykuku/luci-theme-argon.git

# qmodem-next 5G modem feed
src-git modem https://github.com/FUjr/modem_feeds.git;main
