#!/bin/sh /etc/rc.common

START=99
USE_PROCD=1
PROG=/usr/sbin/usbwan-watchdog

start_service() {
	[ -x "$PROG" ] || return 0
	procd_open_instance
	procd_set_param command "$PROG"
	procd_set_param respawn 3600 5 5
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}
